update workflows

diff --git a/.github/workflows/development.yml b/.github/workflows/development.yml
--- a/.github/workflows/development.yml
+++ b/.github/workflows/development.yml
@@ -39,63 +39,63 @@ jobs:
       - name: 🔍 lint code
         run: pnpm check:lint
 
-  # test:
-  #   needs: lint
-  #   name: 🧪 Run tests
-  #   runs-on: ubuntu-latest
-  #   timeout-minutes: 60
-  #   steps:
-  #     - name: ☁️ checkout repository
-  #       uses: actions/checkout@v4
+  test:
+    needs: lint
+    name: 🧪 Run tests
+    runs-on: ubuntu-latest
+    timeout-minutes: 60
+    steps:
+      - name: ☁️ checkout repository
+        uses: actions/checkout@v4
 
-  #     - name: "🔧 setup pnpm"
-  #       uses: pnpm/action-setup@v3
-  #       with:
-  #         version: 9
+      - name: "🔧 setup pnpm"
+        uses: pnpm/action-setup@v3
+        with:
+          version: 9
 
-  #     - name: "🔧 setup node"
-  #       uses: actions/setup-node@v4
-  #       with:
-  #         node-version: 20
-  #         cache: "pnpm"
+      - name: "🔧 setup node"
+        uses: actions/setup-node@v4
+        with:
+          node-version: 20
+          cache: "pnpm"
 
-  #     - name: 📦 install dependencies
-  #       run: pnpm install
+      - name: 📦 install dependencies
+        run: pnpm install
 
-  #     - name: 🎭 install playwright
-  #       run: pnpm playwright install --with-deps --only-shell
+      - name: 🎭 install playwright
+        run: pnpm playwright install --with-deps --only-shell
 
-  #     - name: 🧪 run tests
-  #       run: |
-  #         pnpm test | tee output.log
-  #         if grep -q -e "Error: A snapshot doesn't exist at" -e "Screenshot comparison failed" output.log; then
-  #           echo "Playwright tests failed due to a snapshot issue."
-  #           echo "SNAPSHOT_DIFFERENCES=true" >> $GITHUB_ENV
-  #           exit 1
-  #         elif grep -q "failed" output.log; then
-  #           echo "Playwright tests failed due to a non-snapshot issue."
-  #           exit 1
-  #         fi
+      - name: 🧪 run tests
+        run: |
+          pnpm test | tee output.log
+          if grep -q -e "Error: A snapshot doesn't exist at" -e "Screenshot comparison failed" output.log; then
+            echo "Playwright tests failed due to a snapshot issue."
+            echo "SNAPSHOT_DIFFERENCES=true" >> $GITHUB_ENV
+            exit 1
+          elif grep -q "failed" output.log; then
+            echo "Playwright tests failed due to a non-snapshot issue."
+            exit 1
+          fi
 
-  #     - name: 🗄️ archive artifacts
-  #       uses: actions/upload-artifact@v4
-  #       id: artifact-upload
-  #       if: ${{ !cancelled() }}
-  #       with:
-  #         name: playwright-report
-  #         path: packages/web-components/playwright-report/
-  #         retention-days: 30
+      - name: 🗄️ archive artifacts
+        uses: actions/upload-artifact@v4
+        id: artifact-upload
+        if: ${{ !cancelled() }}
+        with:
+          name: playwright-report
+          path: packages/web-components/playwright-report/
+          retention-days: 30
 
-  #     - name: ✍️ comment on PR with report link
-  #       uses: thollander/actions-comment-pull-request@v3
-  #       if: ${{ failure() && env.SNAPSHOT_DIFFERENCES == 'true' }}
-  #       with:
-  #         message: |
-  #           > [!CAUTION]
-  #           > Playwright visual snapshot differences were detected.
-  #           > You can download the [report](${{ steps.artifact-upload.outputs.artifact-url }}) file.
+      - name: ✍️ comment on PR with report link
+        uses: thollander/actions-comment-pull-request@v3
+        if: ${{ failure() && env.SNAPSHOT_DIFFERENCES == 'true' }}
+        with:
+          message: |
+            > [!CAUTION]
+            > Playwright visual snapshot differences were detected.
+            > You can download the [report](${{ steps.artifact-upload.outputs.artifact-url }}) file.
 
-  #           To approve the snapshot changes and update the snapshots, please comment:
-  #           ```
-  #           /approve-snapshots
-  #           ```
+            To approve the snapshot changes and update the snapshots, please comment:
+            ```
+            /approve-snapshots
+            ```
